api = "0.7"

[buildpack]
homepage = "https://github.com/paketo-buildpacks/yarn"
id = "paketo-buildpacks/yarn"
name = "Paketo Buildpack for Yarn"
sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[[buildpack.licenses]]
type = "Apache-2.0"
uri = "https://github.com/paketo-buildpacks/yarn/blob/main/LICENSE"

[metadata]
include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
pre-package = "./scripts/build.sh"
[metadata.default_versions]
yarn = "1.*"

[[metadata.dependencies]]
cpe = "cpe:2.3:a:yarnpkg:yarn:1.22.18:*:*:*:*:*:*:*"
id = "yarn"
licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
name = "Yarn"
purl = "pkg:generic/yarn@1.22.18?checksum=816e5c073b3d35936a398d1fe769ebbcd517298e3510b649e8fc67cd3a62e113&download_url=https://github.com/yarnpkg/yarn/releases/download/v1.22.18/yarn-v1.22.18.tar.gz"
checksum = "sha256:24ca2294411ea89ae6342a56e7194d7bbcb0710fa40042fdfb503b55d0181baf"
source = "https://github.com/yarnpkg/yarn/releases/download/v1.22.18/yarn-v1.22.18.tar.gz"
source-checksum = "sha256:816e5c073b3d35936a398d1fe769ebbcd517298e3510b649e8fc67cd3a62e113"
stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy", "*"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-1.22.4-any-stack-24ca2294.tgz"
version = "1.22.4"

[[metadata.dependencies]]
cpe = "cpe:2.3:a:yarnpkg:yarn:1.22.19:*:*:*:*:*:*:*"
id = "yarn"
licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
name = "Yarn"
purl = "pkg:generic/yarn@1.22.19?checksum=732620bac8b1690d507274f025f3c6cfdc3627a84d9642e38a07452cc00e0f2e&download_url=https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-v1.22.19.tar.gz"
checksum = "sha256:0057c1c90c3eadc953cc3e6772fd1477179d30a7007ac46ca148dd7bfab1d188"
source = "https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-v1.22.19.tar.gz"
source-checksum = "sha256:732620bac8b1690d507274f025f3c6cfdc3627a84d9642e38a07452cc00e0f2e"
stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy", "*"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn_1.22.10_linux_noarch_any-stack_0057c1c9.tgz"
version = "1.22.10"

[[metadata.dependency-constraints]]
constraint = "1.*"
id = "yarn"
patches = 2

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.jammy"

[[stacks]]
id = "*"
