name: Push Buildpackage

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-tags: true

      - name: Package
        run: |
             ./scripts/package.sh --version 1.0.0
             echo "Packaging the buildpack..."
             echo ${{secrets.PUSH_TOKEN}} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
             sudo skopeo copy "oci-archive:build/buildpackage.cnb" "docker://docker.io/a1flecke/yarn-buildpack:${{ github.sha }}"

