name: Push Buildpackage

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-tags: true

      - name: Package
        run: |
             ./scripts/package.sh --version 1.0.0
             echo "Packaging the buildpack..."
             echo ${{secrets.PUSH_TOKEN}} | docker login ghcr.io -u USERNAME --password-stdin
             echo "docker://${{ env.REGISTRY }}/a1flecke/yarn/yarn-buildpack:${{ github.sha }}"
             ls -al build
             docker image load --input build/buildpack.tgz
             docker image ls 
             sudo skopeo copy "oci-archive:build/buildpackage.cnb" "docker://${{ env.REGISTRY }}/a1flecke/yarn/yarn-buildpack:${{ github.sha }}"

