name: Push Buildpackage

on: push

env:
  REGISTRIES_FILENAME: "registries.json"

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-tags: true

      - name: Package
        run: ./scripts/package.sh --version 1.0.0

      - name: Get buildpack type
        id: get_buildpack_type
        run: |
          
          if [ -f "extension.toml" ]; then
            echo "buildpack_type=extension" >> "$GITHUB_OUTPUT"
          else
            echo "buildpack_type=buildpack" >> "$GITHUB_OUTPUT"
          fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildpackage
          path: |
            build/buildpack.tgz
            build/buildpackage.cnb