name: Push Buildpackage

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-tags: true

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package
        run: |
             ./scripts/package.sh --version 1.0.0
             echo "Packaging the buildpack..."
             echo "docker://${{ env.REGISTRY }}/a1flecke/yarn/yarn-buildpack:${{ github.sha }}"
             sudo skopeo copy "oci-archive:build/buildpackage.cnb" "docker://${{ env.REGISTRY }}/a1flecke/yarn/yarn-buildpack:${{ github.sha }}"

