name: Push Buildpackage

on:
  release:
    types:
      - published
env:
  REGISTRIES_FILENAME: "registries.json"

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: integration
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-tags: true

      - name: Package
        run: ./scripts/package.sh --version 1.0.0

      - name: Get buildpack type
        id: get_buildpack_type
        with:
          assets: |
            [
              {
                "path": "build/buildpack.tgz",
                "name": "${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.tgz",
                "content_type": "application/gzip"
              },
              {
                "path": "build/buildpackage.cnb",
                "name": "${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.cnb",
                "content_type": "application/gzip"
              }
            ]
        run: |
          
          if [ -f "extension.toml" ]; then
            echo "buildpack_type=extension" >> "$GITHUB_OUTPUT"
          else
            echo "buildpack_type=buildpack" >> "$GITHUB_OUTPUT"
          fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildpackage
          path: |
            build/buildpack.tgz
            build/buildpackage.cnb

  failure:
    name: Alert on Failure
    runs-on: ubuntu-22.04
    needs: [push]
    if: ${{ always() && needs.push.result == 'failure' }}
    steps:
      - name: File Failure Alert Issue
        uses: paketo-buildpacks/github-config/actions/issue/file@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          label: "failure:push"
          comment_if_exists: true
          issue_title: "Failure: Push Buildpackage workflow"
          issue_body: |
            Push Buildpackage workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
          comment_body: |
            Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}